# ======================================= #
# ============= Main Menu =============== #
# ======================================= #
[[mainmenu]]
name = "Home"
url = "/"
pre = ""
weight = 1

[[mainmenu]]
name = "About"
url = "/about"
pre = ''
weight = 2

[[mainmenu]]
name = "Posts"
url = "/posts"
pre = ''
weight = 3

[[mainmenu]]
name = "Contact"
url = "/contact"
pre = ''
weight = 4
