# Author information
author = "Armoghan-ul-Mohmin"
github = "https://github.com/Armoghan-ul-Mohmin"
facebook = "https://facebook.com/armoghan"
twitter = "@armoghan16"
# Open Graph (OG) image for social media sharing
og_image = "/images/og.png"
# Site information
sitename = "Sleek Stream"
Description = "Custom Hugo theme with Tailwind CSS, SCSS, Summery Panel, Admin Panel, and Light/Dark theme support."
# Navbar Logo
Logo = '' # Leave blank for no logo
# Website Preloder
Preloder = true

# Custom settings (you can adjust these based on your needs)
[Custom]
Css = false # Disable custom CSS (set to true if you want to enable)
Js = false # Disable custom JavaScript (set to true if you want to enable)

# Navigation settings
[Nav]
enableThemeToggle = true # Enable theme toggle in the navigation
enableSearch = true # Enable search in the navigation

[Footer]
showFootermenu = true
showCopyright = true

[About]
Name = 'Armoghan-ul-Mohmin'
Description = 'I`m a student studying Digital Forensics and Cybersecurity at Lahore Garrison University. I`m passionate about understanding and protecting digital systems. I love solving digital mysteries and keeping up with the latest trends in cybersecurity. My goal is to become a cybersecurity expert and help make the digital world safer.'
Description_2 = 'In addition to my studies, I actively participate in cybersecurity communities and attend workshops to gain practical experience. I believe that hands-on learning is crucial in this field. With each challenge I face and each problem I solve, I`m one step closer to achieving my dream of making the digital realm a more secure place for everyone'

[[Doing]]
Name = 'Web Design'
Image = ''
Description = 'The most modern and high-quality design made at a professional level.'

[[Doing]]
Name = 'Web Development'
Image = ''
Description = 'Professional-level website development expertise delivered with precision and excellence.'

[[Doing]]
Name = 'Digital Forensic'
Image = ''
Description = 'I`m excited to help with open-source projects, making digital security better for everyone.'

[[Doing]]
Name = 'Photography'
Image = ''
Description = 'I capture high-quality photos across diverse categories with a professional touch.'

[Contact]
Email = 'Armoghan16@gmail.com'
